title: "Kyla's Portfolio"
description: "Hi! I'm Kyla, a second-year Computer Science student at Douglas college. I love to play games, create games
and also watch other people play games. I’m passionate about playing games, creating games, and even watching others play. 
I believe that creativity and curiosity are the driving forces that push the boundaries of what’s possible."


theme: jekyll-theme-minimal
