itle: "Kyla's Portfolio"
photo: /assets/IMG_1195.jpg
description: "Hi! I'm Kyla and welcome to my portfolio showcasing my game development projects, research, and VR game development work."

author:
  avatar           : /assets/IMG_1195.jpg
  name             : Zin Wai (Kyla) Myint
  pronouns         : "she/her"  
  bio              : I am a Second Year Computing Science 
  location         : Vancouver, Canada
  email            : "zinwaimyint23@gmail.ccom" 

nav:
  - title: Home
    url: /  
  - title: Projects
    url: /projects
  - title: About Me
    url: /about
  - title: Contact
    url: /contact

theme: jekyll-theme-minimal 
dark_mode: true  
accent_color: "#A0B682"

social:
  - icon: "github"
    url: "https://github.com/yourusername"
  - icon: "linkedin"
    url: "https://www.linkedin.com/in/yourusername/"

markdown: kramdown
paginate: 5
