# Site Settings
title: "Kyla's Portfolio"
description: "Welcome to my portfolio showcasing my game development projects, research, and VR game development work."
author:
  name: "Zin Wai (Kyla) Myint"
  email: "zinwaimyint23@gmail.com"
  location: "Vancouver, Canada"
  pronouns: "she/her"
  photo: ./assets/IMG_1195.jpg 
  bio: "Game Developer | VR Researcher | ESL Learning Enthusiast"

theme: jekyll-theme-cayman
