title: "Kyla's Portfolio"
avatar: /assets/IMG_1195.heic
description: "Hi! I'm Kyla and currently a Second Year Computer Science student at Douglas College."

author:
  name             : "Zin Wai (Kyla) Myint"
  pronouns         : "she/her"  
  location         : "Vancouver, Canada"
  email            : "zinwaimyint23@gmail.ccom" 

nav:
  - title: Home
    url: /  
  - title: Projects
    url: /projects
  - title: About Me
    url: /about
  - title: Contact
    url: /contact

theme: jekyll-theme-minimal 
dark_mode: true  
accent_color: "#A0B682"

social:
  - icon: "github"
    url: "https://github.com/yourusername"
  - icon: "linkedin"
    url: "https://www.linkedin.com/in/yourusername/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
      
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
