title: "Kyla's Portfolio"
avatar: /assets/IMG_1195.jpg
description: "Hi! I'm Kyla and currently a Second Year Computer Science student at Douglas College."

author:
  name             : "Zin Wai (Kyla) Myint"
  pronouns         : "she/her"  
  location         : "Vancouver, Canada"
  email            : "zinwaimyint23@gmail.ccom" 

nav:
  - title: Home
    url: /  
  - title: Projects
    url: /projects
  - title: About Me
    url: /about
  - title: Contact
    url: /contact

theme: jekyll-theme-minimal 
dark_mode: true  
accent_color: "#A0B682"

social:
  - icon: "github"
    url: "https://github.com/yourusername"
  - icon: "linkedin"
    url: "https://www.linkedin.com/in/yourusername/"

sass:
  style: compressed
custom_css: /assets/custom.css
